site_name: OpenBoxes
site_description: OpenBoxes documentation
site_author: Justin Miranda
site_url: https://docs.openboxes.com/en/
repo_url: https://github.com/openboxes/openboxes
theme:
  name: material
  logo: img/logo.svg
  palette:
    primary: white
    accent: blue
  features:
    - navigation.tabs
    - toc.integration
use_directory_urls: true
copyright: Copyright &copy; 2010-2021, OpenBoxes
google_analytics: ['UA-37396941-2', 'openboxes.com']
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - About:
    - Introduction: index.md
    - Architecture: about/architecture.md
    - Benefits: about/benefits.md
    - Considerations: about/considerations.md
    - Release Notes: about/release-notes.md
  - Installation Guide:
    - Getting Started: installation/index.md
    - Installation:
      - Ubuntu:
        - Ubuntu 18.04:
          - Overview: installation/ubuntu1804/index.md
          - Requirements: installation/ubuntu1804/requirements.md
          - Hosting: installation/ubuntu1804/hosting.md
          - Ubuntu: installation/ubuntu1804/ubuntu.md
          - Java: installation/ubuntu1804/java.md
          - Tomcat: installation/ubuntu1804/tomcat.md
          - MySQL: installation/ubuntu1804/mysql.md
          - Apache: installation/ubuntu1804/apache.md
          - Configuration: installation/ubuntu1804/configuration.md
          - Deployment: installation/ubuntu1804/deployment.md
          - Troubleshooting: installation/ubuntu1804/troubleshooting.md
        - Ubuntu 18.04 (Grails v3):
          - Overview: installation/ubuntu1804-grails3/index.md
          - Hosting: installation/ubuntu1804-grails3/hosting.md
          - Ubuntu: installation/ubuntu1804-grails3/ubuntu.md
          - Java: installation/ubuntu1804-grails3/java.md
          - MySQL: installation/ubuntu1804-grails3/mysql.md
          - Application: installation/ubuntu1804-grails3/application.md
          - Apache/Nginx: installation/ubuntu1804-grails3/webserver.md
          - Deployment: installation/ubuntu1804-grails3/deployment.md
          - Configuration: installation/ubuntu1804-grails3/configuration.md
          - Troubleshooting: installation/ubuntu1804-grails3/troubleshooting.md
        - Ubuntu 16.04:
          - Instructions: installation/ubuntu1604.md
          - Notes: installation/ubuntu1604-notes.md
        - Ubuntu 14.04: installation/ubuntu1404.md
        - Advanced: installation/advanced.md
      - Docker: installation/docker.md
      - Mac OS: installation/macos.md
      - Windows: installation/windows.md
    - Upgrading: upgrading/index.md
  - Configuration Guide:
    - Overview: configuration/index.md
    - Tomcat AJP: configuration/ajp.md
    - Apache HTTPS: configuration/https.md
    - Database Connection: configuration/database.md
    - Email: configuration/email.md
    - OpenBoxes: configuration/application.md
    - Sentry: configuration/sentry.md
    - Example: configuration/example.md
  - User Guide: user-guide/index.md
  - Developer Guide:
    - Introduction: developer-guide/index.md
    - Getting Started: developer-guide/getting-started.md
    - Contributing: developer-guide/contributing.md
    - Syncing a Fork: developer-guide/syncing-a-fork.md
    - Tagging a Release: developer-guide/tagging.md
    - Troubleshooting: developer-guide/troubleshooting.md
    - Release Lifecycle:
      - Overview: developer-guide/release/index.md
      - Plan: developer-guide/release/plan.md
      - Develop: developer-guide/release/develop.md
      - Prepare: developer-guide/release/prepare.md
      - Test: developer-guide/release/testing.md
      - Finalize: developer-guide/release/finalize.md
      - Document: developer-guide/release/document.md
      - Publish: developer-guide/release/publish.md
      - Deploy: developer-guide/release/deploy.md
      - Cleanup: developer-guide/release/cleanup.md
    - Hotfix Lifecycle: developer-guide/hotfix/index.md
  - API Guide:
    - Overview: api-guide/index.md
    - Generic API: api-guide/generic.md
    - Getting Started: api-guide/getting-started.md
    - Searching: api-guide/lookup.md
    - Core:
        - Identifiers: api-guide/identifier.md
        - Internal Locations: api-guide/internalLocation.md
        - Localizations: api-guide/localization.md
        - Locations: api-guide/location.md
        - Reason Codes: api-guide/reasonCode.md
    - Products:
        - Categories: api-guide/category.md
        - Products: api-guide/product.md
    - Stock Movements:
        - Stock Movement: api-guide/stockMovement.md
        - Stock Movement Item: api-guide/stockMovementItem.md
        - Stock Movement Status: api-guide/stockMovementStatus.md
        - Putaway: api-guide/putaway.md
        - Receiving: api-guide/receiving.md
  - Support:
    - Overview: support/index.md


